server:
  port: 80

spring:
  rabbitmq:
    host: rabbitmq-sat
    port: 15673
    username: admin
    password: admin123
    virtual-host: satVHost

platform:
  base-url: https://sat.example.com/api/

logging:
  config: classpath:log4j-sat.xml