apiVersion: v1
kind: Service
metadata:
  name: springboot-app-scaffold-uat
  labels:
    app: springboot-app-scaffold-uat
  namespace: uat
spec:
  type: NodePort
  ports:
  - port: 13085
    targetPort: 9000
    nodePort: 13085
    name: web
  - port: 29285
    targetPort: 29285
    nodePort: 29285
    name: rmi
  clusterIP: 10.96.0.81
  selector:
    app: springboot-app-scaffold-uat
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: springboot-app-scaffold-uat-pdb
  namespace: uat
spec:
  selector:
    matchLabels:
      app: springboot-app-scaffold-uat
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: springboot-app-scaffold-uat
  namespace: uat
spec:
  selector:
    matchLabels:
      app: springboot-app-scaffold-uat
  serviceName: springboot-app-scaffold-uat-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: springboot-app-scaffold-uat
      annotations:
        prometheus.io/path: /springboot-app-scaffold/prometheus
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: springboot-app-scaffold
        imagePullPolicy: Always
        image: "registry.cn-shenzhen.aliyuncs.com/devops-app/$IMAGE_VERSION_NAME"
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "0.5"
        volumeMounts:
          - name: logs
            mountPath: /tmp/springboot-app-scaffold/uat
          - name: javamelody
            mountPath: /tmp/springboot-app-scaffold/javamelody
        ports:
        - containerPort: 9000
          name: web
        - containerPort: 29285
          name: rmi
        env:
        - name: env
          value: uat
        - name: RMI_PORT
          value: "29285"
        - name: RMI_HOST
          value: "rmi.example.com"
        - name: JAVA_XMS
          value: "256m"
        - name: JAVA_XMX
          value: "512m"
        - name: MONITOR_HOST
          value: "monitoring.example.com"
        livenessProbe:
          httpGet:
            path: /springboot-app-scaffold/health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /springboot-app-scaffold/health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
      nodeSelector:
          name: k8s-mk2
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 114.114.114.114
          - 8.8.8.8
        searches:
          - ns1.svc.cluster.local
          - mysql.example.com
          - db.example.com
          - rmi.example.com
          - monitoring.example.com
        options:
          - name: ndots
            value: "2"
          - name: edns0
      volumes:
        - name: logs
          hostPath:
            path: /nfs-k8s/shared/logs/springboot-app-scaffold/k8s/uat
            type: DirectoryOrCreate
        - name: javamelody
          hostPath:
            path: /nfs-k8s/shared/jvm/springboot-app-scaffold/k8s/uat
            type: DirectoryOrCreate